services:
  mysql:
    image: mysql:latest
    container_name: karela_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: karela
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.

  redis:
    image: redis:latest
    container_name: karela_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
